global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jumbo-store-api'

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['store-api:8080']
        labels:
          application: 'jumbo-store-api'
          environment: 'production'

